/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Existing rail tokens — preserved
        rail: {
          bg: '#050816',
          'bg-surface': '#071120',
          'bg-elevated': '#0B1328',
          surface: '#10192E',
          'surface-2': '#131E37',
          accent: '#4E7CFF',
          success: '#20D97C',
          warning: '#FFB547',
          danger: '#FF5757',
          secondary: '#8FA7D9',
          border: '#1A2540',
          'border-2': '#243154',
        },
        // DESIGN.md — Industrial Light palette
        'slate-50':  '#f8fafc',
        'slate-100': '#f1f5f9',
        'slate-200': '#e2e8f0',
        'slate-300': '#cbd5e1',
        'slate-400': '#94a3b8',
        'slate-500': '#64748b',
        'slate-700': '#334155',
        'slate-900': '#0f172a',
        'red-50':    '#fef2f2',
        'red-200':   '#fecaca',
        'red-600':   '#dc2626',
        'amber-50':  '#fffbeb',
        'amber-200': '#fde68a',
        'amber-500': '#f59e0b',
        'amber-600': '#d97706',
        'blue-50':   '#eff6ff',
        'blue-200':  '#bfdbfe',
        'blue-600':  '#2563eb',
        'blue-700':  '#1d4ed8',
        'green-50':  '#f0fdf4',
        'green-200': '#bbf7d0',
        'green-500': '#22c55e',
        'green-600': '#16a34a',
      },
      fontFamily: {
        // Existing — preserved
        heading: ['IBM Plex Sans', 'sans-serif'],
        body:    ['IBM Plex Sans', 'sans-serif'],
        mono:    ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
        // DESIGN.md named families
        'display-lg':   ['IBM Plex Sans', 'sans-serif'],
        'panel-header': ['IBM Plex Sans', 'sans-serif'],
        'body-base':    ['IBM Plex Sans', 'sans-serif'],
        'label-caps':   ['IBM Plex Sans', 'sans-serif'],
        'data-mono':    ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
        'data-mono-sm': ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
        'data-mono-bold':['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        // Existing — preserved
        'heading-1': ['44px', { lineHeight: '1.1', fontWeight: '700' }],
        'heading-2': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'heading-3': ['18px', { lineHeight: '1.3', fontWeight: '600' }],
        body:        ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        label:       ['12px', { lineHeight: '1.5', fontWeight: '500' }],
        // DESIGN.md type scale
        'display-lg':    ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'panel-header':  ['14px', { lineHeight: '20px', letterSpacing: '0.05em',  fontWeight: '600' }],
        'body-base':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps':    ['11px', { lineHeight: '14px', letterSpacing: '0.07em',  fontWeight: '700' }],
        'data-mono':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'data-mono-bold':['13px', { lineHeight: '18px', fontWeight: '700' }],
        'data-mono-sm':  ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
      borderRadius: {
        // DESIGN.md: 2px universal radius, "machined" look
        'base':    '2px',
        DEFAULT:   '2px',
        sm:        '2px',
        md:        '4px',
        lg:        '4px',
        xl:        '6px',
        '2xl':     '8px',
        full:      '9999px',
      },
      spacing: {
        // DESIGN.md 4px baseline grid
        'baseline':        '4px',
        'xs':              '4px',
        'sm':              '8px',
        'md':              '12px',
        'lg':              '16px',
        'xl':              '24px',
        'gutter':          '4px',
        'margin-desktop':  '12px',
        'row-height-dense':'28px',
      },
      transitionDuration: {
        hover:  '120ms',
        panel:  '180ms',
        page:   '250ms',
      },
      transitionTimingFunction: {
        default: 'ease',
      },
    },
  },
  plugins: [],
}